version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: hongjunyan/japanese-news-backend:2.0.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hongjunyan/japanese-news-frontend:2.0.0